name:  first

on:  push

jobs:
    job1:
        name: First job
        runs-on:  ubuntu-latest
        steps:
        - name:  step1
          run: echo "Today is $(date) on Ubuntu"
    job2:
        name:  Second job
        runs-on: windows-latest
        steps:
          - name:  step2
            run:  "Get-Date"
    job3:
        name:  MacJob
        runs-on: macos-latest
        steps:
          - name: step1
            run: echo "Today is $(date) on MacOS"
    job4:
        name: Fourth job
        runs-on: ubuntu-16.04
        needs: [job1,job2,job3]
        steps:
        - name:  step1
          run: echo "Today is $(date) on Ubuntu-16"
    job5:
        name: selfjhu
        runs-on: self-hosted

        steps:
          - name: step1
            run:
              echo "Today is $(date) on jb machine"
              echo "uname -a"
